apiVersion: apps/v1
kind: Deployment
metadata:
  name: manggoormy
  namespace: manggoormy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manggoormy
  template:
    metadata:
      labels:
        app: manggoormy
    spec:
      containers:
        - name: manggoormy
          image: 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com/manggoormy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 15
          periodSeconds: 30
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 30
          periodSeconds: 30