apiVersion: v1
kind: Service
metadata:
  name: manggoormy
  namespace: manggoormy
spec:
  selector:
    app: manggoormy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080