# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Image Build & Push Image to ECR & Deploy EKS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 환경 yml 파일 생성 - application.yml
    - name: make application.yml
      run: |
        mkdir ./src/main/resources
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.YML }}" > ./application.yml
      shell: bash

    # addition executable permission
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # clean build with gradle without test
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test

    # AWS Configure
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    # AWS login ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build Image
    - name: Build Docker Image
      run: docker build -t 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com/manggoormy:latest .

    # Image Tag
    - name: tag to Image
      run: docker tag manggoormy:latest 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com/manggoormy:latest

    # Push Image to ECR
    - name: Push Image to ECR
      run: docker push 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com/manggoormy:latest